[workspace]
authors = ["Krisztian Szucs <szucs.krisztian@gmail.com>"]
channels = [
  "https://prefix.dev/pontoneer",
  "https://conda.modular.com/max-nightly/",
  "conda-forge"
]
name = "marrow"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
build_python = { cmd = "mojo build -I . python/lib.mojo --emit shared-lib -o python/marrow.so" }
test_mojo = { cmd = "pytest --mojo -v" }
test_python = { cmd = "pytest --python -v", depends-on = ["build_python"] }
test_gpu = { cmd = "pytest --gpu -v" }
test = { cmd = "pytest -v", depends-on = ["build_python"] }
bench_mojo = { cmd = "pytest --benchmark --mojo -v" }
bench_python = { cmd = "pytest --benchmark --python -v", depends-on = ["build_python"] }
bench = { cmd = "pytest --benchmark -v", depends-on = ["build_python"] }
fmt_mojo = { cmd = "mojo format marrow" }
fmt_python = { cmd = "ruff format python" }
fmt = { depends-on = ["fmt_mojo", "fmt_python"] }
package = "mkdir -p package && mojo package marrow -o package/marrow.mojopkg"
docs = { cmd = "quarto render docs/", depends-on = [
  "build_python",
], env = { PYTHONPATH = "python" } }
docs_preview = { cmd = "quarto preview docs/", depends-on = [
  "build_python",
], env = { PYTHONPATH = "python" } }

[feature.package.dependencies]
rattler-build = ">=0.35,<1"

[feature.package.tasks]
package-conda = "rattler-build build --recipe recipe/recipe.yaml --output-dir output"

[environments]
package = { features = ["package"], no-default-feature = true }

[dependencies]
ipython = ">=9.11.0,<10"
jupyter = ">=1.1,<2"
jupyter-cache = ">=1.0,<2"
mojo = ">=0.26.2.0.dev2026030905,<0.27"
pontoneer = ">=0.3.6"
pytest = ">=9.0.2,<10"
pytest-benchmark = ">=5.2.3,<6"
python = ">=3.14.2,<3.15"
quarto = ">=1.6,<2"
ruff = ">=0.14.14,<0.15"

[pypi-dependencies]
pyarrow = ">=23.0.0, <24"
