"""Test rapidhash against C reference implementation vectors.

Reference vectors generated by compiling and running rapidhash.h (v3)
with default seed=0 and default secrets. See:
  https://github.com/Nicoshev/rapidhash
"""

from std.testing import assert_equal, assert_true
from marrow.testing import TestSuite

from marrow.arrays import PrimitiveArray
from marrow.builders import PrimitiveBuilder
from marrow.dtypes import int32, int64, uint64, Int32Type, Int64Type, UInt64Type
from marrow.kernels.hashing import (
    rapidhash,
    _rapidhash_fixed,
    NULL_HASH_SENTINEL,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _assert_hash_eq(h: UInt64Array, idx: Int, expected: UInt64) raises:
    var got = UInt64(h.unsafe_get(idx))
    if got != expected:
        raise Error(
            "rapidhash mismatch at index "
            + String(idx)
            + ": got 0x"
            + hex(got)
            + " expected 0x"
            + hex(expected)
        )


# ---------------------------------------------------------------------------
# int32 test vectors (4 bytes, seed=0)
# ---------------------------------------------------------------------------


def test_rapidhash_int32() raises:
    """Validate vectorized rapidhash[Int32Type] against C reference."""
    var b = Int32Builder(capacity=7)
    b.append(Scalar[int32.native](0))
    b.append(Scalar[int32.native](1))
    b.append(Scalar[int32.native](-1))
    b.append(Scalar[int32.native](42))
    b.append(Scalar[int32.native](1000000))
    b.append(Scalar[int32.native](2147483647))
    b.append(Scalar[int32.native](-2147483648))
    var arr = b.finish()
    var h = rapidhash[Int32Type](arr)

    _assert_hash_eq(h, 0, 0xBA8945AAEC02CEE2)
    _assert_hash_eq(h, 1, 0x2B281F986C8B17D6)
    _assert_hash_eq(h, 2, 0x60486C15260D35CD)
    _assert_hash_eq(h, 3, 0x5EBDF38ED638F7A4)
    _assert_hash_eq(h, 4, 0xA0069A3A9E41DC88)
    _assert_hash_eq(h, 5, 0x90D336B991118909)
    _assert_hash_eq(h, 6, 0x13890D5C06B3EEB0)


# ---------------------------------------------------------------------------
# int64 test vectors (8 bytes, seed=0)
# ---------------------------------------------------------------------------


def test_rapidhash_int64() raises:
    """Validate vectorized rapidhash[Int64Type] against C reference."""
    var b = Int64Builder(capacity=7)
    b.append(Scalar[int64.native](0))
    b.append(Scalar[int64.native](1))
    b.append(Scalar[int64.native](-1))
    b.append(Scalar[int64.native](42))
    b.append(Scalar[int64.native](1000000))
    b.append(Scalar[int64.native](9223372036854775807))
    b.append(Scalar[int64.native](-9223372036854775808))
    var arr = b.finish()
    var h = rapidhash[Int64Type](arr)

    _assert_hash_eq(h, 0, 0x9EFC171AEBCEA1F3)
    _assert_hash_eq(h, 1, 0xBEC178309F44AFBC)
    _assert_hash_eq(h, 2, 0x8A185FBD8550916D)
    _assert_hash_eq(h, 3, 0x46007CEF671E1CDF)
    _assert_hash_eq(h, 4, 0xBAE276403A287B35)
    _assert_hash_eq(h, 5, 0x5A45FC0CE02F9D32)
    _assert_hash_eq(h, 6, 0x772E91684DA5B145)


# ---------------------------------------------------------------------------
# Scalar matches vectorized
# ---------------------------------------------------------------------------


def test_scalar_matches_vectorized() raises:
    """Scalar _rapidhash_fixed produces same output as vectorized rapidhash."""
    var b = Int64Builder(capacity=5)
    b.append(Scalar[int64.native](0))
    b.append(Scalar[int64.native](42))
    b.append(Scalar[int64.native](-1))
    b.append(Scalar[int64.native](999999))
    b.append(Scalar[int64.native](123456789))
    var arr = b.finish()
    var h = rapidhash[Int64Type](arr)

    for i in range(5):
        var scalar_h = _rapidhash_fixed[8](UInt64(arr.unsafe_get(i)))
        var vec_h = UInt64(h.unsafe_get(i))
        if scalar_h != vec_h:
            raise Error("scalar/vectorized mismatch at index " + String(i))


# ---------------------------------------------------------------------------
# Null sentinel
# ---------------------------------------------------------------------------


def test_null_produces_sentinel() raises:
    """Null elements hash to NULL_HASH_SENTINEL."""
    var b = Int64Builder(capacity=3)
    b.append(Scalar[int64.native](42))
    b.append_null()
    b.append(Scalar[int64.native](7))
    var arr = b.finish()
    var h = rapidhash[Int64Type](arr)

    assert_true(UInt64(h.unsafe_get(0)) != NULL_HASH_SENTINEL)
    assert_equal(UInt64(h.unsafe_get(1)), NULL_HASH_SENTINEL)
    assert_true(UInt64(h.unsafe_get(2)) != NULL_HASH_SENTINEL)


def main() raises:
    TestSuite.run[__functions_in_module()]()
