project:
  type: website
  output-dir: _site

website:
  title: "Marrow"
  description: "Apache Arrow in Mojo"
  navbar:
    logo: ../logo.png
    logo-alt: "marrow"
    left:
      - text: "Quickstart"
        href: index.qmd
      - text: "Guides"
        menu:
          - text: "Arrays"
            href: guide/arrays.qmd
          - text: "Compute"
            href: guide/compute.qmd
          - text: "Expressions"
            href: guide/expressions.qmd
          - text: "Type System"
            href: guide/types.qmd
          - text: "PyArrow Interop"
            href: guide/interop.qmd
      - text: "Examples"
        menu:
          - text: "DataFusion UDFs"
            href: examples/datafusion.qmd
    right:
      - icon: github
        href: https://github.com/kszucs/marrow

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    highlight-style: github

execute:
  freeze: auto
  cache: true
