name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  test-linux-x86_64:
    name: test (linux, x86_64)
    runs-on: ubuntu-latest
    env:
      MODULAR_HOME: "/home/runner/.modular"
      FORCE_COLOR: "1"
      PYTEST_ADDOPTS: "--color=yes"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - uses: prefix-dev/setup-pixi@v0.9.4
      with:
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        frozen: true
        environments: dev
    - name: tests
      run: |
        pixi run -e dev test_parallel --no-gpu
        pixi run package

  test-macos-arm64:
    name: test (macos, arm64)
    runs-on: macos-latest
    env:
      MODULAR_HOME: "/Users/runner/.modular"
      FORCE_COLOR: "1"
      PYTEST_ADDOPTS: "--color=yes"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - uses: prefix-dev/setup-pixi@v0.9.4
      with:
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        frozen: true
        environments: dev
    - name: tests
      run: |
        pixi run -e dev test_parallel --no-gpu
        pixi run package

  bench-linux-x86_64:
    name: bench (linux, x86_64)
    runs-on: ubuntu-latest
    env:
      MODULAR_HOME: "/home/runner/.modular"
      FORCE_COLOR: "1"
      PYTEST_ADDOPTS: "--color=yes"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - uses: prefix-dev/setup-pixi@v0.9.4
      with:
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        frozen: true
        environments: bench
    - name: benchmarks
      run: pixi run -e bench bench --no-gpu

  asan-linux-x86_64:
    name: asan (linux, x86_64)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      MODULAR_HOME: "/home/runner/.modular"
      FORCE_COLOR: "1"
      PYTEST_ADDOPTS: "--color=yes"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - uses: prefix-dev/setup-pixi@v0.9.4
      with:
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        frozen: true
        environments: asan
    - name: asan tests
      run: pixi run -e asan test_mojo_asan --no-gpu --no-python
